backend:
  name: git-gateway
  branch: main

media_folder: "uploads"
public_folder: "/uploads"

collections:
  - name: "beats"
    label: "Beats"
    description: "Upload and manage your beats"
    file: "beats.json"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "BPM", name: "bpm", widget: "number" }
      - { label: "Key", name: "key", widget: "string" }
      - { label: "Price", name: "price", widget: "number" }
      - { label: "Beat File", name: "file", widget: "file" }
